name: Deploy to Aliyun ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ALIYUN_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.ALIYUN_HOST }} "
            # 确保目录存在
            mkdir -p /var/www/CCL
            cd /var/www/CCL
            
            # 强制重置Git配置
            if [ -d .git ]; then
              git remote set-url origin https://github.com/GaLimonkey/CCL.git
              git fetch --force origin
              git reset --hard origin/main
            else
              git init
              git remote add origin https://github.com/GaLimonkey/CCL.git
              git fetch
              git checkout -t origin/main
            fi
            
            # 设置Python虚拟环境
            if [ ! -d venv ]; then
              python3 -m venv venv
            fi
            
            # 安装依赖
            source venv/bin/activate
            pip install --disable-pip-version-check --no-cache-dir -r requirements.txt
            
            # 设置系统服务（如果不存在）
            if [ ! -f /etc/systemd/system/solar_quote.service ]; then
              sudo bash -c 'cat > /etc/systemd/system/solar_quote.service <<EOF
              [Unit]
              Description=Solar Quote Service
              After=network.target

              [Service]
              User=root
              WorkingDirectory=/var/www/CCL
              ExecStart=/var/www/CCL/venv/bin/python /var/www/CCL/run.py
              Restart=always

              [Install]
              WantedBy=multi-user.target
              EOF'
              sudo systemctl daemon-reload
              sudo systemctl enable solar_quote
            fi
            
            sudo systemctl restart solar_quote
          "
