name: Deploy to Aliyun ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ALIYUN_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.ALIYUN_HOST }} "
            # 更新代码（使用强制拉取覆盖本地修改）
            cd /var/www/CCL
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            
            # 激活虚拟环境并更新依赖
            source venv/bin/activate
            pip install --disable-pip-version-check --no-cache-dir -r requirements.txt
            
            # 重启服务
            sudo systemctl restart solar_quote
            
            # 验证部署
            echo '部署完成，服务状态：'
            systemctl status solar_quote --no-pager
          "
