name: Deploy to Aliyun ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ALIYUN_SSH_KEY }}

      - name: Setup Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.ALIYUN_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.ALIYUN_HOST }} "
            # 确保目录存在
            mkdir -p /var/www/CCL || exit 1
            # 克隆或更新代码
            if [ -d /var/www/CCL/.git ]; then
              cd /var/www/CCL
              git pull origin main
            else
              git clone https://github.com/Galimoney/CCL.git /var/www/CCL
              cd /var/www/CCL
            fi
            # 安装依赖并重启服务
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart solar_quote
          "
