name: Deploy to Aliyun ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ALIYUN_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.ALIYUN_HOST }} "
            # 清理旧目录（保留备份）
            sudo mkdir -p /var/www/backups
            sudo mv /var/www/CCL /var/www/backups/CCL_$(date +%Y%m%d%H%M%S) 2>/dev/null || true
            
            # 使用SSH协议克隆仓库
            git clone git@github.com:GaLimonkey/CCL.git /var/www/CCL
            
            # 设置目录权限
            sudo chown -R www-data:www-data /var/www/CCL
            sudo chmod -R 755 /var/www/CCL
            
            # 设置Python虚拟环境
            cd /var/www/CCL
            python3 -m venv venv
            source venv/bin/activate
            
            # 安装依赖
            if [ -f requirements.txt ]; then
              pip install --disable-pip-version-check --no-cache-dir -r requirements.txt
            else
              echo 'Flask==2.0.1' > requirements.txt
              pip install -r requirements.txt
            fi
            
            # 配置系统服务
            sudo tee /etc/systemd/system/solar_quote.service <<EOF
            [Unit]
            Description=Solar Quote Service
            After=network.target

            [Service]
            User=www-data
            WorkingDirectory=/var/www/CCL
            ExecStart=/var/www/CCL/venv/bin/python /var/www/CCL/run.py
            Restart=always
            Environment="PYTHONPATH=/var/www/CCL"

            [Install]
            WantedBy=multi-user.target
            EOF
            
            # 启动服务
            sudo systemctl daemon-reload
            sudo systemctl enable solar_quote
            sudo systemctl restart solar_quote
            
            # 验证部署
            echo '部署完成，服务状态：'
            systemctl status solar_quote --no-pager
          "
