name: Deploy to Aliyun ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS || 'github.com' }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.ALIYUN_HOST }} "
            cd /var/www/CCL
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart solar_quote
          "
